-define(COLOR_BLACK, "\e[0;30m").
-define(COLOR_DARK_RED, "\e[0;31m").
-define(COLOR_DARK_GREEN, "\e[0;32m").
-define(COLOR_DARK_YELLOW, "\e[0;33m").
-define(COLOR_DARK_BLUE, "\e[0;34m").
-define(COLOR_DARK_MAGENTA, "\e[0;35m").
-define(COLOR_DARK_CYAN, "\e[0;36m").
-define(COLOR_DARK_WHITE, "\e[0;37m").

-define(COLOR_BRIGHT_BLACK, "\e[0;90m").
-define(COLOR_BRIGHT_RED, "\e[0;91m").
-define(COLOR_BRIGHT_GREEN, "\e[0;92m").
-define(COLOR_BRIGHT_YELLOW, "\e[0;93m").
-define(COLOR_BRIGHT_BLUE, "\e[0;94m").
-define(COLOR_BRIGHT_MAGENTA, "\e[0;95m").
-define(COLOR_BRIGHT_CYAN, "\e[0;96m").
-define(COLOR_WHITE, "\e[0;97m").
